- .github/ISSUE_TEMPLATE/task.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7144
**Description**
The new yaml syntax was used to have an issue form. You can play with it before merging at https://github.com/gaetanmaisse/issues-form/issues/new/choose
For details, see: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
Screenshot
> Add an issue template for Task

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.15.9
> Changelog for APIM - 3.15.9

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.10.16
> Changelog for APIM - 3.10.16

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.10.17
> Changelog for APIM - 3.10.17

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.15.10
> Changelog for APIM - 3.15.10

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.15.11
> Changelog for APIM - 3.15.11

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.17.4
> Changelog for APIM - 3.17.4

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.0
> Changelog for APIM - 3.18.0

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.15.12
> Changelog for APIM - 3.15.12

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.1
> Changelog for APIM - 3.18.1

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.2
> Changelog for APIM - 3.18.2

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.10.18
> Changelog for APIM - 3.10.18

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.3
> Changelog for APIM - 3.18.3

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.15.13
> Changelog for APIM - 3.15.13

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.17.5
> Changelog for APIM - 3.17.5

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.4
> Changelog for APIM - 3.18.4

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.10.19
> Changelog for APIM - 3.10.19

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.17.6
> Changelog for APIM - 3.17.6

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.5
> Changelog for APIM - 3.18.5

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.6
> Changelog for APIM - 3.18.6

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.15.14
> Changelog for APIM - 3.15.14

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.15.15
> Changelog for APIM - 3.15.15

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.7
> Changelog for APIM - 3.18.7

- CHANGELOG-v3.adoc
docs: add omitted #8387 ticket to APIM 3.18.7 changelog
> docs: add omitted #8387 ticket to APIM 3.18.7 changelog

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.8
> Changelog for APIM - 3.18.8

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.15.16
> Changelog for APIM - 3.15.16

- CHANGELOG-v3.adoc
Generate changelog for version APIM - 3.18.9
> Changelog for APIM - 3.18.9
